Make the submit script more flexible

diff --git a/SubmitPbsJob b/SubmitPbsJob
--- a/SubmitPbsJob
+++ b/SubmitPbsJob
@@ -2,52 +2,79 @@
 
 #==================================== help ====================================#
 
-if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-    echo "SubmitPbsJob: Submit PBS script to Torque queue"
-    echo
-    echo "Usage: From a directory containing this script, run:"
-    echo "    ./SubmitPbsJob JobName PbsScript [RunConfig [InitPos [ExeFile]]]"
-    echo "where"
-    echo "    JobName       Name of the PBS job (the argument to qsub after -N"
-    echo "                  switch); required"
-    echo "    PbsScript     Name of the pbs script; required"
-    echo "    RunConfig     Location of the run config file; optional; if not"
-    echo "                  supplied, runConfig.txt from current directory will"
-    echo "                  be used"
-    echo "    InitPos       Initial sphere location and radius; optional; if"
-    echo "                  not supplied, posInitial.txt from current directory"
-    echo "                  be used"
-    echo "    ExeFile       Name of the executable; optional; if not supplied,"
-    echo "                  SphereSimulator.X from current directory will be"
-    echo "                  used"
-fi
+usage() {
+    echo -e "Usage: $0"
+    echo -e "\t-n <name of pbs job>"
+    echo -e "\t-s <path/to/pbs/script>"
+    echo -e "\t[-c <path/to/run/config/file>]"
+    echo -e "\t[-x <path/to/executable>]"
+    echo -e "\t[-i <path/to/initial/location/file>]"
+}
 
 #======================== parse command line arguments ========================#
 
-if [ -z "$1" ]; then
-    echo "ERROR: Job name must be supplied"
+while getopts ":hs:c:i:n:x:" opt; do
+    case $opt in
+        h)
+            usage
+            exit 0
+            ;;
+        n)
+            JOB_NAME=$OPTARG
+            ;;
+        s)
+            PBS_SCRIPT=$OPTARG
+            ;;
+        c)
+            RUN_CONF=$OPTARG
+            ;;
+        x)
+            EXE_FILE=$OPTARG
+            ;;
+        i)
+            INIT_POS=$OPTARG
+            ;;
+        *)
+            echo "Error: Invalid arguments!"
+            usage
+            exit 1
+            ;;
+    esac
+done
+shift $((OPTIND-1))
+
+#=============================== validate input ===============================#
+
+if [ -z $JOB_NAME ]; then
+    echo "Error: Job name must be supplied!"
     exit 1
-else
-    JOB_NAME=$1
+fi
 
-    if [ -z "$2" ]; then
-        echo "ERROR: PBS script name must be supplied"
-        exit 1
-    else
-        PBS_SCRIPT=$2
+if [ -z $PBS_SCRIPT ]; then
+    echo "Error: Path to PBS scrit must be supplied!"
+    exit 1
+elif [ ! -f $PBS_SCRIPT ]; then
+    echo "Error: PBS script path is invalid!"
+    exit 1
+fi
 
-        if [ -n "$3" ]; then
-            RUN_CONF=$3
-            
-            if [ -n "$4" ]; then
-                INIT_POS=$4
+if [ -z $RUN_CONF ]; then
+    RUN_CONF=runConfig.txt
+elif [ ! -f $RUN_CONF ]; then
+    echo "Error: Run config file path is invalid!"
+    exit 1
+fi
 
-                if [ -n "$5" ]; then
-                    EXE_FILE=$5
-                fi
-            fi
-        fi
-    fi
+if [ -z $EXE_FILE ]; then
+    EXE_FILE=SphereSimulator.X
+elif [ ! -f $EXE_FILE ]; then
+    echo "Error: Executable file path is invalid!"
+    exit 1
+fi
+
+if [ ! -f $INIT_POS ]; then
+    echo "Error: Intial position file path is invalid!"
+    exit 1
 fi
 
 #============================= set up directories =============================#
@@ -56,8 +83,7 @@ fi
 CURRDIR=`pwd`
 
 # create a direcotry name using jobname and current time
-UNIQSTR=`date +%Y-%m-%d_%H-%M-%S`"_"$JOB_NAME
-WORKDIR="/scratch/shravan_flux/saibalde/"$UNIQSTR
+WORKDIR="/scratch/shravan_flux/saibalde/"`date +%Y-%m-%d_%H-%M-%S`"_"$JOB_NAME
 
 # create the directory under scratch filesystem
 mkdir $WORKDIR
@@ -65,31 +91,10 @@ mkdir $WORKDIR
 #================================= copy stuff =================================#
 
 cp $PBS_SCRIPT $WORKDIR/jobsub.pbs
-
-if [ -n "$RUN_CONF" ] && [ -f $RUN_CONF ]; then
-    cp $RUN_CONF $WORKDIR/runConfig.txt
-elif [ -f "runConfig.txt" ]; then
-    cp runConfig.txt $WORKDIR/runConfig.txt
-else
-    echo "ERROR: Run configuration file does not exist!"
-    exit 1
-fi
-
-if [ -n "$INIT_POS" ] && [ -f $INIT_POS ]; then
+cp $RUN_CONF $WORKDIR/runConfig.txt
+cp $EXE_FILE $WORKDIR/SphereSimulator.X
+if [ -n "$INIT_POS" ];
     cp $INIT_POS $WORKDIR/posInitial.txt
-elif [ -f "posInitial.txt" ]; then
-    cp posInitial.txt $WORKDIR/posInitial.txt
-else
-    echo "WARNING: Not initial position file, one will be randomly generated"
-fi
-
-if [ -n "$EXE_FILE" ] && [ -f $EXE_FILE ]; then
-    cp $EXE_FILE $WORKDIR/SphereSimulator.X
-elif [ -f "SphereSimulator.X" ]; then
-    cp SphereSimulator.X $WORKDIR/SphereSimulator.X
-else
-    echo "ERROR: Executable file does not exit!"
-    exit 1
 fi
 
 #================================= run script =================================#
